// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_gamedata.proto

#include "player_gamedata.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace game {
PROTOBUF_CONSTEXPR PlayerGamedata::PlayerGamedata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.latest_pos_)*/uint64_t{0u}
  , /*decltype(_impl_.spawn_pos_)*/uint64_t{0u}
  , /*decltype(_impl_.level_)*/0u
  , /*decltype(_impl_.exp_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerGamedataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerGamedataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerGamedataDefaultTypeInternal() {}
  union {
    PlayerGamedata _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerGamedataDefaultTypeInternal _PlayerGamedata_default_instance_;
}  // namespace game
static ::_pb::Metadata file_level_metadata_player_5fgamedata_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_player_5fgamedata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_player_5fgamedata_2eproto = nullptr;

const uint32_t TableStruct_player_5fgamedata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::PlayerGamedata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game::PlayerGamedata, _impl_.latest_pos_),
  PROTOBUF_FIELD_OFFSET(::game::PlayerGamedata, _impl_.spawn_pos_),
  PROTOBUF_FIELD_OFFSET(::game::PlayerGamedata, _impl_.level_),
  PROTOBUF_FIELD_OFFSET(::game::PlayerGamedata, _impl_.exp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::game::PlayerGamedata)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::game::_PlayerGamedata_default_instance_._instance,
};

const char descriptor_table_protodef_player_5fgamedata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025player_gamedata.proto\022\004game\"S\n\016PlayerG"
  "amedata\022\022\n\nlatest_pos\030\001 \001(\004\022\021\n\tspawn_pos"
  "\030\002 \001(\004\022\r\n\005level\030\003 \001(\r\022\013\n\003exp\030\004 \001(\rb\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_player_5fgamedata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_player_5fgamedata_2eproto = {
    false, false, 122, descriptor_table_protodef_player_5fgamedata_2eproto,
    "player_gamedata.proto",
    &descriptor_table_player_5fgamedata_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_player_5fgamedata_2eproto::offsets,
    file_level_metadata_player_5fgamedata_2eproto, file_level_enum_descriptors_player_5fgamedata_2eproto,
    file_level_service_descriptors_player_5fgamedata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_player_5fgamedata_2eproto_getter() {
  return &descriptor_table_player_5fgamedata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_player_5fgamedata_2eproto(&descriptor_table_player_5fgamedata_2eproto);
namespace game {

// ===================================================================

class PlayerGamedata::_Internal {
 public:
};

PlayerGamedata::PlayerGamedata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game.PlayerGamedata)
}
PlayerGamedata::PlayerGamedata(const PlayerGamedata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerGamedata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.latest_pos_){}
    , decltype(_impl_.spawn_pos_){}
    , decltype(_impl_.level_){}
    , decltype(_impl_.exp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.latest_pos_, &from._impl_.latest_pos_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.exp_) -
    reinterpret_cast<char*>(&_impl_.latest_pos_)) + sizeof(_impl_.exp_));
  // @@protoc_insertion_point(copy_constructor:game.PlayerGamedata)
}

inline void PlayerGamedata::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.latest_pos_){uint64_t{0u}}
    , decltype(_impl_.spawn_pos_){uint64_t{0u}}
    , decltype(_impl_.level_){0u}
    , decltype(_impl_.exp_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerGamedata::~PlayerGamedata() {
  // @@protoc_insertion_point(destructor:game.PlayerGamedata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerGamedata::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerGamedata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerGamedata::Clear() {
// @@protoc_insertion_point(message_clear_start:game.PlayerGamedata)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.latest_pos_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.exp_) -
      reinterpret_cast<char*>(&_impl_.latest_pos_)) + sizeof(_impl_.exp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerGamedata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 latest_pos = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.latest_pos_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 spawn_pos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.spawn_pos_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 level = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 exp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.exp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerGamedata::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.PlayerGamedata)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 latest_pos = 1;
  if (this->_internal_latest_pos() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_latest_pos(), target);
  }

  // uint64 spawn_pos = 2;
  if (this->_internal_spawn_pos() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_spawn_pos(), target);
  }

  // uint32 level = 3;
  if (this->_internal_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_level(), target);
  }

  // uint32 exp = 4;
  if (this->_internal_exp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_exp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.PlayerGamedata)
  return target;
}

size_t PlayerGamedata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.PlayerGamedata)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 latest_pos = 1;
  if (this->_internal_latest_pos() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_latest_pos());
  }

  // uint64 spawn_pos = 2;
  if (this->_internal_spawn_pos() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_spawn_pos());
  }

  // uint32 level = 3;
  if (this->_internal_level() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_level());
  }

  // uint32 exp = 4;
  if (this->_internal_exp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_exp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerGamedata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerGamedata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerGamedata::GetClassData() const { return &_class_data_; }


void PlayerGamedata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerGamedata*>(&to_msg);
  auto& from = static_cast<const PlayerGamedata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game.PlayerGamedata)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_latest_pos() != 0) {
    _this->_internal_set_latest_pos(from._internal_latest_pos());
  }
  if (from._internal_spawn_pos() != 0) {
    _this->_internal_set_spawn_pos(from._internal_spawn_pos());
  }
  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  if (from._internal_exp() != 0) {
    _this->_internal_set_exp(from._internal_exp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerGamedata::CopyFrom(const PlayerGamedata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.PlayerGamedata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerGamedata::IsInitialized() const {
  return true;
}

void PlayerGamedata::InternalSwap(PlayerGamedata* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerGamedata, _impl_.exp_)
      + sizeof(PlayerGamedata::_impl_.exp_)
      - PROTOBUF_FIELD_OFFSET(PlayerGamedata, _impl_.latest_pos_)>(
          reinterpret_cast<char*>(&_impl_.latest_pos_),
          reinterpret_cast<char*>(&other->_impl_.latest_pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerGamedata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_player_5fgamedata_2eproto_getter, &descriptor_table_player_5fgamedata_2eproto_once,
      file_level_metadata_player_5fgamedata_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::PlayerGamedata*
Arena::CreateMaybeMessage< ::game::PlayerGamedata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::PlayerGamedata >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
